### ISSUE TITLE
[UX Enhancement] Share button

### ISSUE THREAD

**Issue by imabp** [MLH-Fellowship/CryptoDrive#101]
Currently, if you want to share an already shared file on CryptoDrive, it needs to be first downloaded by user, and uploaded and then shared. This is bad UX. 

The following feature will help to overcome this.

Implementing Share feature, on Shared Files Section.
This will enrich UX and avoid unnecessary heads on user

**Comment by ksdkamesh99** [comment]
As a part of the retrospective week, I am working on this issue @imabp @Sameerkash
